import { v4 as uuidv4 } from 'uuid';
import { ROLES, PRODUCT_CATEGORIES, ORDER_STATUS } from '../utils/constants';

// Mock Users
export const mockUsers = [
  {
    id: uuidv4(),
    email: 'admin@solar.com',
    password: 'admin123', // In real app, this would be hashed
    name: 'Admin User',
    role: ROLES.ADMIN,
    avatar: `https://ui-avatars.com/api/?name=Admin+User&background=0ea5e9&color=fff`,
    createdAt: new Date('2024-01-01').toISOString(),
    lastLogin: new Date().toISOString(),
    isActive: true,
  },
  {
    id: uuidv4(),
    email: 'user@solar.com',
    password: 'user123',
    name: 'John Doe',
    role: ROLES.USER,
    avatar: `https://ui-avatars.com/api/?name=John+Doe&background=22c55e&color=fff`,
    createdAt: new Date('2024-01-15').toISOString(),
    lastLogin: new Date().toISOString(),
    isActive: true,
  },
];

// Mock Products
export const mockProducts = [
  {
    id: uuidv4(),
    sku: 'SOL-PAN-001',
    name: '400W Monocrystalline Solar Panel',
    category: 'SOLAR_PANELS',
    subcategory: 'Monocrystalline',
    description: 'High-efficiency monocrystalline solar panel with 21.5% efficiency. Perfect for residential and commercial installations.',
    quantity: 150,
    unitPrice: 299.99,
    supplier: 'SolarTech Inc.',
    manufacturer: 'SunPower',
    warranty: '25 years',
    specifications: {
      wattage: '400W',
      efficiency: '21.5%',
      dimensions: '78x39x1.4 inches',
      weight: '48 lbs',
      cells: '120 half-cut',
    },
    imageUrl: '/api/placeholder/200/200',
    lowStockThreshold: 20,
    location: 'Warehouse A - Rack 12',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: uuidv4(),
    sku: 'SOL-INV-001',
    name: '7.6kW String Inverter',
    category: 'INVERTERS',
    subcategory: 'String',
    description: 'High-efficiency string inverter with integrated monitoring. Compatible with most solar panel configurations.',
    quantity: 45,
    unitPrice: 1899.99,
    supplier: 'InverterPro',
    manufacturer: 'SolarEdge',
    warranty: '12 years',
    specifications: {
      power: '7.6kW',
      efficiency: '99%',
      inputVoltage: '600V',
      outputType: '240V AC',
    },
    imageUrl: '/api/placeholder/200/200',
    lowStockThreshold: 10,
    location: 'Warehouse B - Rack 3',
    createdAt: new Date('2024-01-12').toISOString(),
    updatedAt: new Date('2024-01-12').toISOString(),
  },
  {
    id: uuidv4(),
    sku: 'SOL-BAT-001',
    name: '10kWh Lithium-Ion Battery',
    category: 'BATTERIES',
    subcategory: 'Lithium-ion',
    description: 'High-capacity lithium-ion battery for solar energy storage. Features built-in BMS and 10-year warranty.',
    quantity: 8,
    unitPrice: 5499.99,
    supplier: 'BatteryWorld',
    manufacturer: 'Tesla',
    warranty: '10 years',
    specifications: {
      capacity: '10kWh',
      voltage: '48V',
      chemistry: 'LiFePO4',
      cycles: '6000',
    },
    imageUrl: '/api/placeholder/200/200',
    lowStockThreshold: 5,
    location: 'Warehouse C - Rack 7',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: uuidv4(),
    sku: 'SOL-MNT-001',
    name: 'Roof Mounting Kit - 10 Panels',
    category: 'MOUNTING_STRUCTURES',
    subcategory: 'Roof Mount',
    description: 'Complete roof mounting system for 10 solar panels. Includes rails, clamps, and flashing.',
    quantity: 25,
    unitPrice: 899.99,
    supplier: 'MountingPro',
    manufacturer: 'IronRidge',
    warranty: '20 years',
    specifications: {
      capacity: '10 panels',
      material: 'Aluminum',
      railLength: '20ft',
      includes: 'End clamps, mid clamps, flashing',
    },
    imageUrl: '/api/placeholder/200/200',
    lowStockThreshold: 5,
    location: 'Warehouse A - Rack 5',
    createdAt: new Date('2024-01-18').toISOString(),
    updatedAt: new Date('2024-01-18').toISOString(),
  },
  {
    id: uuidv4(),
    sku: 'SOL-CBL-001',
    name: 'Solar PV Cable - 100ft',
    category: 'CABLES',
    subcategory: 'DC Cables',
    description: '10 AWG solar PV cable with UV protection. Suitable for outdoor installations.',
    quantity: 2,
    unitPrice: 89.99,
    supplier: 'CableTech',
    manufacturer: 'Southwire',
    warranty: '5 years',
    specifications: {
      gauge: '10 AWG',
      length: '100ft',
      insulation: 'XLPE',
      temperature: '-40°C to +90°C',
    },
    imageUrl: '/api/placeholder/200/200',
    lowStockThreshold: 10,
    location: 'Warehouse B - Rack 15',
    createdAt: new Date('2024-01-20').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
  },
];

// Mock Orders
export const mockOrders = [
  {
    id: uuidv4(),
    orderNumber: 'ORD-2024-001',
    userId: mockUsers[1].id,
    items: [
      {
        productId: mockProducts[0].id,
        quantity: 5,
        unitPrice: mockProducts[0].unitPrice,
        productName: mockProducts[0].name,
      },
      {
        productId: mockProducts[3].id,
        quantity: 1,
        unitPrice: mockProducts[3].unitPrice,
        productName: mockProducts[3].name,
      },
    ],
    totalAmount: (5 * 299.99) + 899.99,
    status: ORDER_STATUS.DELIVERED,
    requestedDate: new Date('2024-02-01').toISOString(),
    approvedBy: mockUsers[0].id,
    approvedDate: new Date('2024-02-02').toISOString(),
    shippingAddress: '123 Solar Street, Sunnyville, CA 94000',
    notes: 'Please deliver during business hours',
  },
  {
    id: uuidv4(),
    orderNumber: 'ORD-2024-002',
    userId: mockUsers[1].id,
    items: [
      {
        productId: mockProducts[2].id,
        quantity: 2,
        unitPrice: mockProducts[2].unitPrice,
        productName: mockProducts[2].name,
      },
    ],
    totalAmount: 2 * 5499.99,
    status: ORDER_STATUS.PENDING,
    requestedDate: new Date('2024-02-10').toISOString(),
    approvedBy: null,
    approvedDate: null,
    shippingAddress: '456 Solar Ave, Sunnyville, CA 94000',
    notes: 'Need installation assistance',
  },
  {
    id: uuidv4(),
    orderNumber: 'ORD-2024-003',
    userId: mockUsers[1].id,
    items: [
      {
        productId: mockProducts[1].id,
        quantity: 1,
        unitPrice: mockProducts[1].unitPrice,
        productName: mockProducts[1].name,
      },
      {
        productId: mockProducts[4].id,
        quantity: 3,
        unitPrice: mockProducts[4].unitPrice,
        productName: mockProducts[4].name,
      },
    ],
    totalAmount: 1899.99 + (3 * 89.99),
    status: ORDER_STATUS.APPROVED,
    requestedDate: new Date('2024-02-12').toISOString(),
    approvedBy: mockUsers[0].id,
    approvedDate: new Date('2024-02-13').toISOString(),
    shippingAddress: '789 Solar Blvd, Sunnyville, CA 94000',
    notes: '',
  },
];